version: '3.8'

services:

  db:
    image: postgres
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  adminer:
    image: adminer
    restart: always
    hostname: adminer
    container_name: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  maildev:
    image: maildev/maildev
    restart: always
    hostname: maildev
    container_name: maildev
    ports:
      - 1080:1080  # Web interface
      - 1025:1025  # SMTP server

volumes: 
  postgres:
  redis:
